### ISSUE TITLE
Change output message tuned.service

### ISSUE THREAD

**Issue by velnoxlabs** [scmschmidt/sapconf_saptune_check#1]
Output for ./sapconf_saptune_check sapconf

[ OK ]  sapconf package version 4.1.14
[ OK ]  sapconf tuned profile 'sap-hana' is set
[ OK ]  sapconf.service is active
[ OK ]  sapconf.service is enabled
[ OK ]  tuned.service is active
[ OK ]  tuned.service is disabled

The last 2 messages are confusing. Please change the output to.

[ OK ]  sapconf package version 4.1.14
[ OK ]  sapconf tuned profile 'sap-hana' is set
[ OK ]  sapconf.service is active
[ OK ]  sapconf.service is enabled
[ OK ]  tuned.service is active
[ OK ]  saptuned.service is disabled

**Comment by scmschmidt** [comment]
There is no saptuned.service. The output is correct.
